
//----------------------------------------------------
// The following code was generated by CUP v0.10j
// Fri Dec 04 04:02:18 GMT-08:00 2015
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEP = 37;
  public static final int TABLESWITCH = 33;
  public static final int DTHROWS = 12;
  public static final int DCATCH = 2;
  public static final int USING = 17;
  public static final int PRIVATE = 25;
  public static final int DSOURCE = 11;
  public static final int INTERFACE = 23;
  public static final int STATIC = 28;
  public static final int LOOKUPSWITCH = 32;
  public static final int IS = 18;
  public static final int DINTERFACE = 15;
  public static final int Str = 38;
  public static final int DFIELD = 5;
  public static final int Int = 41;
  public static final int DCLASS = 3;
  public static final int ABSTRACT = 21;
  public static final int EOF = 0;
  public static final int METHOD = 20;
  public static final int error = 1;
  public static final int TRANSIENT = 30;
  public static final int Insn = 40;
  public static final int Word = 39;
  public static final int DSUPER = 10;
  public static final int DLIMIT = 6;
  public static final int EQ = 35;
  public static final int Num = 42;
  public static final int DIMPLEMENTS = 14;
  public static final int FROM = 19;
  public static final int DMETHOD = 8;
  public static final int COLON = 36;
  public static final int NATIVE = 24;
  public static final int PROTECTED = 26;
  public static final int TO = 16;
  public static final int DEND = 4;
  public static final int FINAL = 22;
  public static final int DEFAULT = 34;
  public static final int PUBLIC = 27;
  public static final int VOLATILE = 31;
  public static final int DVAR = 13;
  public static final int SYNCHRONIZED = 29;
  public static final int DSET = 9;
  public static final int DLINE = 7;
}

